"""Initial schema

Revision ID: 5e11af6f2725
Revises: 
Create Date: 2026-06-06 23:27:35.564147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e11af6f2725'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='property_nest'
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('seller_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('property_title', sa.Text(), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('doc_url', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Text(), nullable=False),
    sa.Column('college_name', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('monthly_income', sa.Numeric(), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('lease_duration', sa.Integer(), nullable=False),
    sa.Column('num_occupants', sa.Integer(), nullable=True),
    sa.Column('gov_id_url', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_nest.properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Text(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('meet_url', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_nest.properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['property_nest.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('leases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['property_nest.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_nest.properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['property_nest.leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_nest.properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['property_nest.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='property_nest'
    )
    op.drop_table('maintenance_requests')
    op.drop_table('properties')
    op.drop_table('leases')
    op.drop_table('users')
    op.drop_table('seller_requests')
    op.drop_table('user_roles')
    op.drop_table('appointments')
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('marital_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('employment_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('college_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('current_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('move_in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('lease_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_occupants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gov_id_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name=op.f('applications_applicant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('applications_property_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('applications_pkey'))
    )
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preferred_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('preferred_time', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meet_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('appointments_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('appointments_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('appointments_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_table('seller_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('monthly_rent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('doc_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('declaration_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('district', sa.TEXT(), server_default=sa.text("'CHENNAI'::text"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('seller_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('seller_requests_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('leases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('monthly_rent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('leases_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('leases_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('leases_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], name=op.f('leases_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leases_pkey'))
    )
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthly_rent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('properties_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('properties_pkey'))
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], name=op.f('maintenance_requests_lease_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('maintenance_requests_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], name=op.f('maintenance_requests_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_requests_pkey'))
    )
    op.drop_table('maintenance_requests', schema='property_nest')
    op.drop_table('leases', schema='property_nest')
    op.drop_table('appointments', schema='property_nest')
    op.drop_table('applications', schema='property_nest')
    op.drop_table('user_roles', schema='property_nest')
    op.drop_table('seller_requests', schema='property_nest')
    op.drop_table('properties', schema='property_nest')
    op.drop_table('users', schema='property_nest')
    # ### end Alembic commands ###
